/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/friesman.glb -o src/components/Friesman.jsx -r public 
*/

import React, { useRef, useEffect, useMemo } from 'react'
import { Billboard, Text, useAnimations, useGLTF } from "@react-three/drei";
import { SkeletonUtils } from 'three-stdlib';
import { useGraph } from '@react-three/fiber';
import { useFrame } from '@react-three/fiber';
import { lerp } from "three/src/math/MathUtils";
import { useGame } from '../hooks/useGame';

export function Friesman({friesman,...props}) {
  const group = useRef()
  const { scene, materials, animations } = useGLTF('/models/papitas.glb');
  // Skinned meshes cannot be re-used in threejs withoyt cling them 
  const clone= useMemo(()=>SkeletonUtils.clone(scene),[scene]); 
  // useGraph creates two flat object collections for nodes and meterials
  const {nodes} = useGraph(clone); 
  const { actions } = useAnimations(animations, group)
  const nameMaterial = useRef(); 
  const {isFrismanAttackable} = useGame(); 

  useEffect(()=>{
    actions["Run"].time= Math.random()* actions["Run"].getClip().duration; 
    actions["Run"].play(); 
  },[])

  useFrame((_, delta)=>{
      if(friesman.dead){
          group.current.position.z= -40;
      }else{
        group.current.position.z= lerp(group.current.position.z,0,delta *2)
      }
      nameMaterial.current.opacity = lerp(
        nameMaterial.current.opacity,
        isFrismanAttackable(friesman) ? 1 : 0,
        delta * 2
      );
  })

  return (
    <group ref={group} {...props} dispose={null}>
    {/* NAME */}
    <Billboard position-y={6}>
        <Text fontSize={0.42} font="fonts/PixelifySans-Regular.ttf">
          {friesman.name}
          <meshStandardMaterial
            color="red"
            emissive={"orange"}
            emissiveIntensity={2}
            toneMapped={false}
            ref={nameMaterial}            
          />
        </Text>
      </Billboard>      
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
          castShadow
          receiveShadow
          name="_100Avatars_118_COOLFRIES" geometry={nodes._100Avatars_118_COOLFRIES.geometry} material={materials._118_CoolFries} skeleton={nodes._100Avatars_118_COOLFRIES.skeleton} morphTargetDictionary={nodes._100Avatars_118_COOLFRIES.morphTargetDictionary} morphTargetInfluences={nodes._100Avatars_118_COOLFRIES.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/papitas.glb')
