/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/llorarwoman.glb -o src/components/Perdio.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { LoopRepeat } from "three";

export function Perdio({player,...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/llorarwoman.glb')
  const texture = useTexture(player.userPhotoUrl);

  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    Object.keys(actions).forEach((key) => {
      actions[key].loop = LoopRepeat;
      actions[key].clampWhenFinished = false;
      actions[key].play();
    });
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="mesh_char_061" geometry={nodes.mesh_char_061.geometry} material={materials._058_Shiro} skeleton={nodes.mesh_char_061.skeleton} morphTargetDictionary={nodes.mesh_char_061.morphTargetDictionary} morphTargetInfluences={nodes.mesh_char_061.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/llorarwoman.glb')
