/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/principal.glb -o src/components/Principal.jsx -r public 
*/

import React, { useRef, useEffect,useMemo } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export function Principal(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/woman.glb');  

  const { actions } = useAnimations(animations, group);

  useEffect(()=>{
    actions["Run"].play(); 
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
          castShadow
          receiveShadow
          name="mesh_char_061" geometry={nodes.mesh_char_061.geometry} material={materials._058_Shiro} skeleton={nodes.mesh_char_061.skeleton} morphTargetDictionary={nodes.mesh_char_061.morphTargetDictionary} morphTargetInfluences={nodes.mesh_char_061.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/woman.glb')
